// how many card copies for different tiers
// ref: https://www.pcgamesn.com/hearthstone/battlegrounds-cards-list
// T1 -> 18, T2 -> 15, T3 -> 13, T4 -> 11, T5 -> 9, T6 -> 6

function HSMinion(name, type, tier, attack, blood, act, flags, count) {
   this.name = name;
   this.type = type;
   this.tier = tier;
   this.attack = attack;
   this.blood = blood;
   this.act = act;
   this.flags = flags;
   this.count = count;
}

function HSHero(name, blood, act, flags) {
   this.name = name;
   this.blood = blood;
   this.act = act;
   this.flags = flags;
}

var HSMinionPool = [
   new HSMinion('', '', 6, 6, 7, {}, {}, 0),
   // Tier 1
   new HSMinion('alleycat', 'beast', 1, 1, 1, [{ battlecry: true, recruit: true, summon: { a: 1, b: 1, type: 'beast'} }], { white: true }, 18),
   new HSMinion('deck swabbie', 'pirate', 1, 2, 2, [{ battlecry: true, recruit: true, upgrade: -1 }], {}, 18),
   new HSMinion('dragonspawn lieutenant', 'dragon', 1, 2, 3, [], { taunt: true }, 18),
   new HSMinion('fiendish servant', 'demon', 1, 2, 1, [{ deathrattle: true, combat: true, buff: { friend: true, random: true, count: 1, a: 'self.attack'  } }], { white: true }, 18),
   new HSMinion('mecharoo', 'mech', 1, 1, 1, [{ deathrattle: true, combat: true, summon: { a: 1, b: 1, type: 'mech' } }], { white: true }, 18),
   new HSMinion('micro machine', 'mech', 1, 1, 2, [{ start: true, recruit: true, buff: { self: true, a: 1 } }], { white: true }, 18),
   new HSMinion('murloc tidecaller', 'murloc', 1, 1, 2, [{ recruit: true, murloc: 'summon', buff: { self: true, a: 1 } }], { blue: true }, 18),
   new HSMinion('murloc tidehunter', 'murloc', 1, 2, 1, [{ battlecry: true, recruit: true, summon: { a: 1, b: 1, type: 'murloc' } }], {}, 18),
   new HSMinion('red whelp', 'dragon', 1, 1, 2, [{ start: true, combat: true, debuf: { enemy: true, count: 1, b: '-friend.dragon' } }], {}, 18),
   new HSMinion('righteous protector', '', 1, 1, 1, [], { white: true, taunt: true, divine_shield: true }, 18),
   new HSMinion('rockpool hunter', 'murloc', 1, 2, 3, [{ battlecry: true, recruit: true, buff: { friend: true, random: false, count: 1, a: 1, b: 1 } }], { white: true }, 18),
   new HSMinion('scallywag', 'pirate', 1, 2, 1, [{ deathrattle: true, combat: true, summon: { a: 1, a: 1, type: 'pirate', attack: true } }], {}, 18),
   new HSMinion('scaveging hyena', 'beast', 1, 2, 2, [{ combat: true, beast: 'dead', buff: { self: true, a: 2, b: 1 } }], { white: true }, 18),
   new HSMinion('selfless hero', '', 1, 2, 1, [{ deathrattle: true, combat: true, buff: { friend: true, random: true, count: 1, divine_shield: true } }], { blue: true }, 18),
   new HSMinion('vulgar homunculus', 'demon', 1, 2, 4, [{ battlecry: true, debuf: { hero: true, b: -2 } }], { white: true, taunt: true }, 18),
   new HSMinion('wrath waver', '', 1, 1, 1, [{ recruit: true, demon: 'summon', debuf: { hero: true, b: -1 }, buff: { self: true, a: 2, b: 2 } }], { white: true, demon: true }, 18),
   // Tier 2
   new HSMinion('arcane cannon', '', 2, 2, 2, [{ combat: true, neighbor: 'attack', debuf: { enemy: true, random: true, count: 1, b: -2 } }], { noattack: true }, 15),
   new HSMinion('freedealing gambler', 'pirate', 2, 3, 3, [{ recruit: true, self: 'seld', buff: { money: 2 } }], {}, 15),
   new HSMinion('glyph guardian', 'dragon', 2, 2, 4, [{ combat: true, self: 'attack', buff: { self: true, a: 'double' } }], {}, 15),
   new HSMinion('harvest golem', 'mech', 2, 2, 3, [{ deathrattle: true, combat: true, summon: { a: 2, b: 1, type: 'mech' } }], { white: true }, 15),
   new HSMinion('imprisoner', 'demon', 2, 3, 3, [{ deathrattle: true, combat: true, summon: { a: 1, b: 1, type: 'demon' } }], { blue: true, taunt: true, }, 15),
   new HSMinion('kaboom bot', 'mech', 2, 2, 2, [{ deathrattle: true, combat: true, debuf: { enemy: true, random: true, count: 1, b: -4 } }], { white: true }, 15),
   new HSMinion('kindly grandmother', 'beast', 2, 1, 1, [{ deathrattle: true, combat: true, summon: { a: 3, b: 2, type: 'beast' } }], { white: true }, 15),
   new HSMinion('metaltooth leaper', 'mech', 2, 3, 3, [{ battlecry: true, recruit: true, buff: { friend: true, count: 7, type: 'mech', a: 2 } }], { blue: true }, 15),
   new HSMinion('murloc warleader', 'murloc', 2, 3, 3, [{ combat: true, buff: { friend: true, noself: true, count: 6, type: 'murloc', a: 2 } }], { purple: true }, 15),
   new HSMinion('nathrezim overseer', 'demon', 2, 2, 3, [{ battlecry: true, recruit: true, buff: { friend: true, noself: true, count: 1, type: 'demon', a: 2, b: 2 } }], { blue: true }, 15),
   new HSMinion('old murk-eye', 'murloc', 2, 2, 4, [{ combat: true, buff: { self: true, a: 'murloc-1' } }], { orange: true }, 15),
   new HSMinion('pogo-hopper', 'mech', 2, 1, 1, [{ battlecry: true, recruit: true, buf: { self: true, a: 'use*2', b: 'use*2' } }], { blue: true }, 15),
   new HSMinion('rabid saurolisk', 'beast', 2, 3, 2, [{ recruit: true, deathrattle1: 'summon', buff: { self: true, a: 1, b: 1 } }], {}, 15),
   new HSMinion('rat pack', 'beast', 2, 2, 2, [{ deathrattle: true, combat: true, summon: { a: 1, b: 1, type: 'beast', count: 'self.attack' } }], { purple: true }, 15),
   new HSMinion('southsea captain', 'pirate', 2, 3, 3, [{ combat: true, buff: { friend: true, noself: true, count: 6, a: 1, b: 1 } }], { purple: true }, 15),
   new HSMinion('spawn of n\'zoth', '', 2, 2, 2, [{ deathrattle: true, combat: true, buff: { friend: true, count: 6, a: 1, b: 1} }], { white: true }, 15),
   new HSMinion('steward of time', 'dragon', 2, 3, 4, [{ recruit:true, self: 'seld', buff: { tavern: true, count: 7, a: 1, b: 1 } }], {}, 15),
   new HSMinion('unstable ghoul', '', 2, 1, 3, [{ deathrattle: true, combat: true, debuf: { enemy: true, friend: true, count: 14, times: 1, b: -1 } }], { white: true }, 15),
   new HSMinion('waxrider togwaggle', '', 2, 1, 2, [{ combat: true, dragon: 'kill', buff: { self: true, a: 2, b: 2 } }], {}, 15),
   new HSMinion('zoobot', 'mech', 2, 3, 3, [{ battlecry: true, recruit: true, buff: { friend: true, random: true, type: ['dragon', 'beast', 'murloc'], a: 1, b: 1 } }], { white: true, murloc: true, beast: true, dargon: true }, 15),
   // Tier 3
   new HSMinion('bloodsail cannoneer', 'pirate', 3, 4, 2, [{ battlecry: true, recruit: true, buff: { friend: true, noself: true, count: 6, a: 3 } }], {}, 13),
   new HSMinion('bronze warden', 'dragon', 3, 2, 1, [], { divine_shield: true, reborn: true }, 13),
   new HSMinion('coldlight seer', 'murloc', 3, 2, 3, [{ battlecry: true, recruit: true, buff: { friend: true, noself: true, type: 'murloc', count: 6, b: 2 } }], { blue: true }, 13),
   new HSMinion('crowd favorite', '', 3, 4, 4, [{ recruit: true, battlecry1: 'summon', buff: { self: true, a: 1, b: 1 } }], { purple: true }, 13),
   new HSMinion('crystalweaver', '', 3, 5, 4, [{ battlecry: true, recruit: true, buff: { friend: true, type: 'demon', count: 6, a: 1, b: 1 } }], { white: true, demon: true }, 13),
   new HSMinion('deflect-o-bot', 'mech', 3, 3, 2, [{ combat: true, mech: 'summon', buff: { self: true, divine_shield: true, a: 1 } }], {}, 13),
   new HSMinion('felfin navigator', 'murloc', 3, 4, 4, [{ battlecry: true, recruit: true, buff: { friend: true, noself: true, type: 'murloc', count: 6, a: 1, b: 1 } }], { white: true }, 13),
   new HSMinion('hangry dragon', 'dragon', 3, 4, 4, [{ start: true, recruit: true, last_win: true, buff: { self: true, a: 2, b: 2 } }], {}, 13),
   new HSMinion('houndmaster', '', 3, 4, 3, [{ battlecry: true, recruit: true, buff: { friend: true, count: 1, type: 'beast', taunt: true, a: 2, b: 2 } }], { beast: true }, 13),
   new HSMinion('imp gang boss', 'demon', 3, 2, 4, [{ combat: true, self: '-b', summon: { a: 1, b: 1, type: 'demon' } }], { white: true }, 13),
   new HSMinion('infested wolf', 'beast', 3, 3, 3, [{ deathrattle: true, combat: true, summon: { a: 1, b: 1, type: 'beast', count: 2 } }], { blue: true }, 13),
   new HSMinion('khadgar', '', 3, 2, 2, [{ recruit: true, act: 'sub_summon_double' }], { orange: true }, 13),
   new HSMinion('monstrous macaw', 'beast', 3, 3, 2, [{ combat: true, self: 'attack', act: 'deadthrattle_trigger' }], {}, 13),
   new HSMinion('pack leader', '', 3, 3, 3, [{ recruit: true, combat: true, beast: 'summon', buff: { target: true, a: 3 } }], { blue: true, beast: true }, 13),
   new HSMinion('piloted shredder', 'mech', 3, 4, 3, [{ deathrattle: true, combat: true, summon: { random: ['...'] } }], { white: true }, 13),
   new HSMinion('replicating menace', 'mech', 3, 3, 1, [{ deathrattle: true, combat: true, summon: { a: 1, b: 1, type: 'mech', count: 3 } }], { blue: true, magnetic: true }, 13),
   new HSMinion('salty looter', 'pirate', 3, 3, 3, [{ recurit: true, pirate: 'summon', buff: { self: true, a: 1, b: 1 } }], {}, 13),
   new HSMinion('screwjank clunker', 'mech', 3, 2, 5, [{ battlecry: true, recruit: true, buff: { friend: true, type: 'mech', count: 1, a: 2, b: 2 } }], { blue: true }, 13),
   new HSMinion('shifter zerus', '', 3, 1, 1, [{ start: true, recruit: true, hand: true, act: 'random_transform' }], { orange: true }, 13),
   new HSMinion('soul juggler', '', 3, 3, 3, [{ combat: true, demon: 'dead', debuf: { enemy: true, random: true, count: 1, b: -3 } }], { demon: true }, 13),
   new HSMinion('the beast', 'beast', 3, 9, 7, [{ deathrattle: true, combat: true, summon: { a: 3, b: 3, type: '', enemy: true } }], { orange: true }, 13),
   new HSMinion('twilight emissary', 'dragon', 3, 4, 4, [{ battlecry: true, recruit: true, buff: { friend: true, noself: true, count: 1, type: 'dragon', a: 2, b: 2 } }], { taunt: true }, 13),
   new HSMinion('yo-ho-ogre', 'pirate', 3, 2, 8, [{ combat: true, self: 'attacked', attack: true }], { taunt: true }, 13),
   // Tier 4
   new HSMinion('annoy-o-module', 'mech', 4, 2, 4, [], { blue: true, magnetic: true }, 11),
   new HSMinion('bolvar, fireblood', '', 4, 1, 7, [{ combat: true, divine_shield: 'lost', buff: { self: true, a: 2 } }], { orange: true, divine_shield: true }, 11),
   new HSMinion('cave hydra', 'beast', 4, 2, 4, [{ combat: true, act: 'attack_neighbor_enemies' }], { white: true }, 11),
   new HSMinion('cobalt scalebane', 'dragon', 4, 5, 5, [{ end: true, recruit: true, buff: { friend: true, noself: true, count: 1, a: 3 } }], { white: true }, 11),
   new HSMinion('defender of argus', '', 4, 2, 3, [{ battlecry: true, recruit: true, buff: { neighbor: true, count: 2, taunt: true, a: 1, b: 1 } }], { blue: true }, 11),
   new HSMinion('drakonid enforcer', 'dragon', 4, 3, 6, [{ combat: true, divine_shield: 'lost', buff: { self: true, a: 2, b: 2 } }], {}, 11),
   new HSMinion('floating watcher', 'demon', 4, 4, 4, [{ recruit: true, hero: 'damaged', buff: { self: true, a: 2, b: 2 } }], { white: true }, 11),
   new HSMinion('goldgrubber', 'pirate', 4, 2, 2, [{ end: true, recruit: true, buff: { self: true, a: 'gold*2', b: 'gold*2' } }], {}, 11),
   new HSMinion('herald of flame', 'dragon', 4, 5, 6, [{ combat: true, overkill: true, debuf: { enemy: true, left: true, b: -3 } }], {}, 11),
   new HSMinion('iron sesei', 'mech', 4, 2, 2, [{ end: true, recruit: true, buff: { friend: true, noself: true, count: 1, type: 'mech', a: 2, b: 2 } }], { blue: true }, 11),
   new HSMinion('mechano-egg', 'mech', 4, 0, 5, [{ deathrattle: true, combat: true, summon: { a: 8, b: 8, type: 'mech' } }], { white: true }, 11),
   new HSMinion('menagerie magician', '', 4, 4, 4, [{ battlecry: true, recruit: true, buff: { friend: true, random: true, type: ['dragon', 'beast', 'murloc'], a: 2, b: 2 } }], { white: true }, 11),
   new HSMinion('ripsnarl captain', 'pirate', 4, 3, 4, [{ combat: true, pirate: 'attack', buff: { target: true, a: 2, b: 2 } }], {}, 11),
   new HSMinion('savannah highmane', 'beast', 4, 6, 5, [{ deathrattle: true, combat: true, summon: { a: 2, b: 2, type: 'beast', count: 2 } }], { blue: true }, 11),
   new HSMinion('security rover', 'mech', 4, 2, 6, [{ combat: true, self: 'damaged', summon: { a: 2, b: 3, type: 'mech', taunt: true } }], { blue: true }, 11),
   new HSMinion('siegebreaker', 'demon', 4, 5, 8, [{ combat: true, buff: { friend: true, noself: true, count: 6, a: 1 } }], { blue: true, taunt: true }, 11),
   new HSMinion('southsea strongarm', 'pirate', 4, 5, 4, [{ battlecry: true, recruit: true, buff: { friend: true, noself: true, count: 1, type: 'pirate', a: 'turn.pirate.bought', b: 'turn.pirate.bought' } }], {}, 11),
   new HSMinion('toxfin', 'murloc', 4, 1, 2, [{ battlecry: true, recruit: true, buff: { friend: true, noself: true, count: 1, type: 'murloc', poisonous: true } }], { white: true }, 11),
   new HSMinion('virmen sensei', '', 4, 4, 5, [{ battlecry: true, recruit: true, buff: { friend: true, type: 'beast', count: 1, a: 2, b: 2 } }], { blue: true, beast: true }, 11),
   // Tier 5
   new HSMinion('annihilan battlemaster', 'demon', 5, 3, 1, [{ battlecry: true, recruit: true, buff: { self: true, b: 'hero.damaged' } }], { purple: true }, 9),
   new HSMinion('baron rivendare', '', 5, 1, 7, [{ combat: true, act: 'deathrattle_double' }], { orange: true }, 9),
   new HSMinion('brann bronzebeard', '', 5, 2, 4, [{ recruit: true, act: 'battlecry_double' }], { orange: true }, 9),
   new HSMinion('cap\'n hoggarr', 'priate', 5, 6, 6, [{ recruit: true, priate: 'bought', buff: { money: 1 } }], {}, 9),
   new HSMinion('goldrinn, the great wolf', 'beast', 5, 4, 4, [{ deathrattle: true, combat: true, buff: { friend: true, noself: true, type: 'beast', count: 6, a: 4, b: 4 } }], { orange: true }, 9),
   new HSMinion('ironhide direhorn', 'beast', 5, 7, 7, [{ combat: true, overkill: true, summon: { a: 5, b: 5, type: 'beast' } }], { white: true }, 9),
   new HSMinion('junkbot', 'mech', 5, 1, 5, [{ combat: true, mech: 'dead', buff: { self: true, a: 2, b: 2 } }], { purple: true }, 9),
   new HSMinion('king bagurgle', 'murloc', 5, 6, 3, [{ battlecry: true, recruit: true, buff: { friend: true, noself: true, count: 6, type: 'murloc', a: 2, b } }, { deathrattle: true, combat: true, buff: { friend: true, noself: true, count: 6, type: 'murloc', a: 2, b: 2 } }], { orange: true}, 9),
   new HSMinion('lightfang enforcer', '', 5, 2, 2, [{ end: true, recruit: true, buff: { friend: true, type: ['murloc', 'mech', 'beast', 'demon', 'pirate', 'dragon'], a: 2, b: 1 } }], { purple: true }, 9),
   new HSMinion('mal\'ganis', 'demon', 5, 9, 7, [{ combat: true, buff: { friend: true, noself: true, type: 'demon', count: 6, a: 2, b: 2 } }], { orange: true }, 9),
   new HSMinion('murozond', 'dragon', 5, 5, 5, [{ battlecry: true, recruit: true, act: 'minion_copy_from_last_enemy' }], {}, 9),
   new HSMinion('nat pagle, extreme angler', 'pirate', 5, 8, 5, [{ combat: true, overkill: true, summon: { a: 0, b: 2, deathrattle: true, act: 'random_gold_minion' } }], {}, 9),
   new HSMinion('primalfin lookout', 'murloc', 5, 3, 2, [{ battlecry: true, recruit: true, act: 'discover_murloc' }], { white: true }, 9),
   new HSMinion('razorgore, the untamed', 'dragon', 5, 2, 4, [{ end: true, recruit: true, buff: { self: true, a: 'friend.dragon', b: 'friend.dragon' } }], {}, 9),
   new HSMinion('seabreaker goliath', 'pirate', 5, 6, 7, [{ combat: true, overkill: true, buff: { friend: true, noself: true, count: 6, type: 'pirate', a: 2, b: 2 } }], { windfury: true }, 9),
   new HSMinion('sneed\'s old shredder', 'mech', 5, 5, 7, [{ deathrattle: true, combat: true, summon: { noself: true, orange: true } }], { orange: true }, 9),
   new HSMinion('strongshell scavenger', '', 5, 2, 3, [{ battlecry: true, recruit: true, buff: { friend: true, type: 'taunt', a: 2, b: 2 } }], { blue: true }, 9),
   new HSMinion('voidlord', 'demon', 5, 3, 9, [{ deathrattle: true, combat: true, summon: { a:1, b: 3, type: 'demon', count: 3 } }], { purple: true }, 9),
   // Tier 6
   new HSMinion('dread admiral eliza', 'pirate', 6, 6, 7, [{ combat: true, pirate: 'attack', buff: { friend: true, a: 1, b: 1, count: 7 } }], {}, 6),
   new HSMinion('foe reaper 4000', 'mech', 6, 6, 9, [{ combat: true, act: 'attack_neighbor_enemies' }], { orange: true }, 6),
   new HSMinion('gentle megasaur', 'beast', 6, 5, 4, [{ battlecry: true, recruit: true, act: 'murloc_adapt' }], { purple: true, murloc: true }, 6),
   new HSMinion('ghastcoiler', 'beast', 6, 7, 7, [{ deathrattle: true, combat: true, summon: { noself: true, type: 'deathrattle', count: 2 } }], {}, 6),
   new HSMinion('imp mama', 'demon', 6, 6, 10, [{ combat: true, self: 'damaged', summon: { random: ['...'], taunt: true } }], {}, 6),
   new HSMinion('kalecgos, arcane aspeet', 'dragon', 6, 4, 12, [{ recruit: true, battlecry1: 'summon', buff: { friend: true, type: 'dragon', a: 1, b: 1, count: 7 } }], {}, 6),
   new HSMinion('kangor\'s apprentiee', '', 6, 3, 6, [{ deathrattle: true, combat: true, summon: { type: 'mech.dead', count: 2 } }], { purple: true, mech: true }, 6),
   new HSMinion('maexxna', 'beast', 6, 2, 8, [], { orange: true, poisonous: true }, 6),
   new HSMinion('mama bear', 'beast', 6, 5, 5, [{ recruit: true, combat: true, beast: 'summon', buff: { target: true, a: 5, b: 5 } }], { purple: true }, 6),
   new HSMinion('nadina the red', '', 6, 7, 4, [{ deathrattle: true, combat: true, buff: { friend: true, type: 'dragon', count: 6, divine_shield: true } }], { dragon: true }, 6),
   new HSMinion('the tide razor', '', 6, 6, 4, [{ deathrattle: true, combat: true, summon: { random: ['...'], count: 3 }  }], { pirate: true }, 6),
   new HSMinion('zapp slywick', '', 6, 7, 10, [{ combat: true, act: 'attack_lowesta_enemy' }], { windfury: true }, 6)
];

var HSHeroPool = [
   new HSHero('A.F. Kay', 40, { nom: true, recruit: true, turn1: { money: 0 }, turn2: { money: 0 }, turn3: { card: { random: ['...'], count: 2 } } }, {}),
   new HSHero('Alexstrasza', 40, { nom: true, recruit: true, tier5: { card: { random: ['...'], count: 2 } } }, {}),
   new HSHero('Aranna Starseeker', 40, { nom: true, recruit: true, refresh: 7, act: 'tevern.cap=7' }, {}),
   new HSHero('Arch-Villain Rafaam', 40, { nom: true, combat: true, act: 'minion_copy_from_enemy_first_dead' }, {}),
   new HSHero('Bartendotron', 40, { nom: true, recruit: true, buff: { start_upgrade: -1 } }, {}),
   new HSHero('Captain Eudora', 40, { m: 1, recruit: true, card: { aggregator: 4, gold: true } }, {}),
   new HSHero('Captain Hooktusk', 40, { m: 0, recruit: true, remove: 'friend', card: { target: true, tier: -1 } }, {}),
   new HSHero('Dancin\' Deryl', 40, { nom: true, recruit: true, any: 'sold', buff: { tevern: true, random: true, a: 1, b: 1, times: 2 } }, {}),
   new HSHero('Deathwing', 40, { nom: true, combat: true, buff: { friend: true, enemy: true, a: 2 } }, {}),
   new HSHero('Edwin VanCleef', 40, { m: 1, recruit: true, buff: { friend: true, a: 'turn.any.bought', b: 'turn.any.bought' } }, {}),
   new HSHero('Elise Starseeker', 40, { nom: true, recruit: true, tevern: 'upgrade', card: { tier: 0, choose: 3 } }, {}),
   new HSHero('Fungalmanncer Flurgl', 40, { nom: true, recruit: true, murloc: 'sold', summon: { tier: 0, type: 'murloc', count: 1, tevern: true } }, {}),
   new HSHero('Galakrond', 40, { m: 1, recruit: true, transform: { tier: +1, friend: true, tevern: true } }, {}),
   new HSHero('George the Fallen', 40, { m: 3, recruit: true, buff: { friend: true, count: 1, divine_shield: true } }, {}),
   new HSHero('Illidan Stormrage', 40, { nom: true, combat: true, start: true, act: 'left_right_attack' }, {}),
   new HSHero('Infinite Toki', 40, { m: 1, recruit: true, summon: { tier: +1, tevern: true, refresh: true } }, {}),
   new HSHero('Kael\'thas Sunstrider', 40, { nom: true, recruit: true, buff: { bought: true, aggregator: 3, a: 2, b: 2 } }, {}),
   new HSHero('Lady Vashj', 40, { nom: true, recruit: true, tevern: 'upgrade', summon: { tevern: true, tier: +1, refresh: false }}, {}),
   new HSHero('Lich Baz\'hial', 40, { m: 0, recruit: true, debuf: { hero: true, b: -2 }, card: { money: 1 } }, {}),
   new HSHero('Lord Jaraxxus', 40, { m: 1, recruit: true, buff: { friend: true, type: 'demon', count: 7, a: 1, b: 1 } }, {}),
   new HSHero('Maiev Shadowsong', 40, { m: 1, recruit: true, buff: { tevern: true, count: 1, domant: true, turn_aggragator: 2, a: 1, b: 1 } }, {}),
   new HSHero('Malygos', 40, { m: 0, recruit: true, transform: { friend: true, tevern: true, tier: 0 } }, {}),
   new HSHero('Millhouse Manastorm', 40, { nom: true, recruit: true, debuf: { start_upgrade: +1 }, act: 'minion_2_money' }, {}),
   new HSHero('Millificent Manastorm', 40, { nom: true, recruit: true, buff: { friend: true, type: 'mech', a: 1, b: 1 } }, {}),
   new HSHero('Nefarian', 40, { m: 1, combat: true, start: true, debuf: { enemy: true, count: 7, b: -1 } }, {}),
   new HSHero('Nozdormu', 40, { nom: true, recruit: true, act: 'first_refresh_0_money' }, {}),
   new HSHero('Patches the Pirate', 40, { m: 'aggregator=4', recruit: true, act: 'buy_pirate_reduce_1_money', card: { tier: 0, type: 'pirate' }}, {}),
   new HSHero('Patchwerk', 50, {}, {}),
   new HSHero('Pyramad', 40, { m: 1, recruit: true, buf: { friend: true, count: 1, random: true, b: 4 } }, {}),
   new HSHero('Queen Wagtoggle', 40, { m: 1, recruit: true, buf: { type: ['dragon', 'beast', 'pirate', 'mech', 'demon', 'murloc'], friend: true, random: true, a: 2 }}, {}),
   new HSHero('Reno Jackson', 40, { m: 2, recruit: true, once: true, buff: { friend: true, count: 1, gold: true } }, {}),
   new HSHero('Shudderwock', 40, { m: 1, recruit: true, act: 'next_battlecry_double' }, {}),
   new HSHero('Sindragosa', 40, { nom: true, recruit: true, end: true, act: 'fronzen_minion_a1_b1' }, {}),
   new HSHero('Sir Finley Mrrgglton', 40, { nom: true, once: true, transform: { self: true, random: true, choose: 3 } }, {}),
   new HSHero('Skycap\'n Kragg', 40, { m: 'turn.n', recruit: true, once: true }, {}),
   new HSHero('The Curator', 40, { nom: true, recruit: true, once: true, summon: { a: 1, b: 1, type: 'any' } }, {}),
   new HSHero('The Great Akazamzarak', 40, { m: 2, combat: true, secret: { choose: 2 } }, {}),
   new HSHero('The Lich King', 40, { m: 1, combat: true, buff: { friend: true, count: 1, reborn: true }}, {}),
   new HSHero('The Rat King', 40, { nom: true, recruit: true, any: 'bought', buff: { is: true, random: ['murloc', 'beast', 'demon', 'mech', 'pirate', 'dragon'], a: 1, b: 2 } }, {}),
   new HSHero('Yogg-Saron, Hope\'s End', 40, { m: 2, recruit: true, buy: { random: true }, buff: { target: true, a: 2, b: 2 } }, {}),
   new HSHero('Ysera', 40, { nom: true, recruit: true, start: true, summon: { tevern: true, type: 'dragon', tier: 0 } }, {})
];
